version: "3.8"

services:
  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: umkm-backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/dist:/app/dist
    environment:
      - NODE_ENV=production
      - DATABASE_URL=localhost://umkm_user:P@ssw0rd@localhost:3306/umkm_erp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: umkm-frontend
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
 